import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "./_components/header";

export const metadata: Metadata = {
	title: "Clerk Next.js Quickstart",
	description: "Generated by create next app",
};

const nunito = Nunito({ subsets: ["latin"] });

const localization = {
	socialButtonsBlockButton: "GitHubでログインする",
	signIn: {
		start: {
			title: "ログイン",
			subtitle: "現在GitHubでのログインのみ対応しています。",
		},
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider localization={localization}>
			<html lang="ja">
				<body className={`${nunito.className} antialiased bg-slate-50 text-slate-950`}>
					<Header />
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
